# Generated by Django 3.1.6 on 2021-02-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_drivercomment_usertrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrip',
            name='acception',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
